ALTER TABLE Nurse
ADD COLUMN IF NOT EXISTS shift_start VARCHAR(10) DEFAULT '09:00',
ADD COLUMN IF NOT EXISTS shift_end VARCHAR(10) DEFAULT '17:00';

ALTER TABLE Receptionist
ADD COLUMN IF NOT EXISTS shift_start VARCHAR(10) DEFAULT '09:00',
ADD COLUMN IF NOT EXISTS shift_end VARCHAR(10) DEFAULT '17:00';

ALTER TABLE WardBoy
ADD COLUMN IF NOT EXISTS shift_start VARCHAR(10) DEFAULT '09:00',
ADD COLUMN IF NOT EXISTS shift_end VARCHAR(10) DEFAULT '17:00';
